// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChE1wVPHWDNu3B06Eb-dKO4vSZ_9Jh0-I',
    appId: '1:1021702189899:web:995fe264e1fd4efb58aece',
    messagingSenderId: '1021702189899',
    projectId: 'chat-app-22c5c',
    authDomain: 'chat-app-22c5c.firebaseapp.com',
    storageBucket: 'chat-app-22c5c.appspot.com',
    measurementId: 'G-94G0CY964E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuRFWYqyz_qpPQnDf_OTWhBx-x8KapNmg',
    appId: '1:1021702189899:android:c431fa5418b757e558aece',
    messagingSenderId: '1021702189899',
    projectId: 'chat-app-22c5c',
    storageBucket: 'chat-app-22c5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmkj6F8i6qKs0SU94tSUfX-L5vMbSsswk',
    appId: '1:1021702189899:ios:5e40d58aae61e0fa58aece',
    messagingSenderId: '1021702189899',
    projectId: 'chat-app-22c5c',
    storageBucket: 'chat-app-22c5c.appspot.com',
    iosClientId: '1021702189899-08mk0cgfj9ocsj6e2sll7tlpof7fp862.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmkj6F8i6qKs0SU94tSUfX-L5vMbSsswk',
    appId: '1:1021702189899:ios:1bed1d881396dffa58aece',
    messagingSenderId: '1021702189899',
    projectId: 'chat-app-22c5c',
    storageBucket: 'chat-app-22c5c.appspot.com',
    iosClientId: '1021702189899-7m8bdp2lcl1ppu70g9f75uvk24g9mkc7.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
